spring.datasource.url=jdbc:postgresql://localhost:5432/api_financeira
spring.datasource.username=postgres
spring.datasource.password=suasenha  ? mude aqui

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true

jwt.secret=minha-chave-secreta-super-segura-financeiro-api-2024
jwt.expiration=86400000